CREATE TABLE `airline_operations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoiceId` varchar(255) NOT NULL,
	`airline` varchar(100) NOT NULL,
	`passengerName` text NOT NULL,
	`route` varchar(100),
	`emissionDate` varchar(20),
	`ticketNumber` varchar(50),
	`tariff` int,
	`tax` int,
	`cardRAV` int,
	`commission` int,
	`incentive` int,
	`discount` int,
	`taxAmount` int,
	`fee` int,
	`adminFee` int,
	`netAmount` int,
	`duTax` int,
	`observation` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `airline_operations_id` PRIMARY KEY(`id`)
);
